name: PR assignment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          teams: gluestack-ui-reviewers
          numOfAssignee: 1
